spiderJson = {"nodes":[
{"weight":68,"rank":19.0, "id":1, "url":"https://www.crawler-test.com"},
{"weight":1,"rank":0.0, "id":2, "url":"https://www.crawler-test.com/mobile/separate_desktop"},
{"weight":1,"rank":0.0, "id":3, "url":"https://www.crawler-test.com/mobile/desktop_with_AMP_as_mobile"},
{"weight":1,"rank":0.0, "id":7, "url":"https://www.crawler-test.com/mobile/separate_desktop_with_different_links_in"},
{"weight":1,"rank":0.0, "id":12, "url":"https://www.crawler-test.com/mobile/dynamic"},
{"weight":1,"rank":0.0, "id":14, "url":"https://www.crawler-test.com/mobile/no_mobile_configuration"},
{"weight":1,"rank":0.0, "id":15, "url":"https://www.crawler-test.com/mobile/other_desktop_that_links_to_the_same_mobile_pages"},
{"weight":1,"rank":0.0, "id":19, "url":"https://www.crawler-test.com/mobile/no_mobile_with_amp"},
{"weight":1,"rank":0.2742939223961174, "id":22, "url":"https://www.crawler-test.com/mobile/amp_as_desktop_amp_and_mobile"},
{"weight":1,"rank":0.0, "id":24, "url":"https://www.crawler-test.com/mobile/separate_desktop_irregular_media"},
{"weight":1,"rank":0.0, "id":36, "url":"https://www.crawler-test.com/encoding/page_titles_character_encoded"},
{"weight":1,"rank":0.0, "id":54, "url":"https://www.crawler-test.com/titles/duplicate_title/bar"},
{"weight":1,"rank":0.0, "id":58, "url":"https://www.crawler-test.com/titles/title_over_max"},
{"weight":1,"rank":0.0, "id":59, "url":"https://www.crawler-test.com/titles/title_warning"},
{"weight":1,"rank":0.0, "id":67, "url":"https://www.crawler-test.com/robots_protocol/robots_excluded_duplicate_description"},
{"weight":1,"rank":0.0, "id":79, "url":"https://www.crawler-test.com/robots_protocol/robots_excluded_blank_line"},
{"weight":1,"rank":0.0, "id":85, "url":"https://www.crawler-test.com/robots_protocol/robots_meta_none"},
{"weight":1,"rank":0.0, "id":88, "url":"https://www.crawler-test.com/robots_protocol/x_robots_multiple_directives"},
{"weight":1,"rank":0.0, "id":90, "url":"https://www.crawler-test.com/robots_protocol/multiple_googlebot_directive_meta_tag"},
{"weight":1,"rank":0.0, "id":92, "url":"https://www.crawler-test.com/robots_protocol/canonicalised_with_noindex"},
{"weight":1,"rank":0.0, "id":96, "url":"https://www.crawler-test.com/redirects/redirect_3_302"},
{"weight":1,"rank":0.0, "id":97, "url":"https://www.crawler-test.com/redirects/redirect_4_307"},
{"weight":1,"rank":0.0, "id":106, "url":"https://www.crawler-test.com/redirects/meta_redirect_2"},
{"weight":1,"rank":0.0, "id":109, "url":"https://www.crawler-test.com/redirects/external_meta_redirect"},
{"weight":1,"rank":0.0, "id":113, "url":"https://www.crawler-test.com/redirects/url_redirect_chains"},
{"weight":1,"rank":0.2742939223961174, "id":124, "url":"https://www.crawler-test.com/javascript/window-location-function-absolute"}],
"links":[
{"source":0,"target":0,"value":3},
{"source":0,"target":1,"value":3},
{"source":0,"target":2,"value":3},
{"source":0,"target":3,"value":3},
{"source":0,"target":4,"value":3},
{"source":0,"target":5,"value":3},
{"source":0,"target":6,"value":3},
{"source":0,"target":7,"value":3},
{"source":0,"target":8,"value":3},
{"source":0,"target":9,"value":3},
{"source":0,"target":10,"value":3},
{"source":0,"target":11,"value":3},
{"source":0,"target":12,"value":3},
{"source":0,"target":13,"value":3},
{"source":0,"target":14,"value":3},
{"source":0,"target":15,"value":3},
{"source":0,"target":16,"value":3},
{"source":0,"target":17,"value":3},
{"source":0,"target":18,"value":3},
{"source":0,"target":19,"value":3},
{"source":0,"target":20,"value":3},
{"source":0,"target":21,"value":3},
{"source":0,"target":22,"value":3},
{"source":0,"target":23,"value":3},
{"source":0,"target":24,"value":3},
{"source":0,"target":25,"value":3},
{"source":1,"target":0,"value":3},
{"source":2,"target":0,"value":3},
{"source":3,"target":0,"value":3},
{"source":4,"target":0,"value":3},
{"source":5,"target":0,"value":3},
{"source":6,"target":0,"value":3},
{"source":7,"target":0,"value":3},
{"source":9,"target":0,"value":3},
{"source":10,"target":0,"value":3},
{"source":11,"target":0,"value":3},
{"source":12,"target":0,"value":3},
{"source":13,"target":0,"value":3},
{"source":14,"target":0,"value":3},
{"source":15,"target":0,"value":3},
{"source":16,"target":0,"value":3},
{"source":17,"target":0,"value":3},
{"source":18,"target":0,"value":3},
{"source":19,"target":0,"value":3},
{"source":20,"target":0,"value":3},
{"source":21,"target":0,"value":3},
{"source":22,"target":0,"value":3},
{"source":23,"target":0,"value":3},
{"source":24,"target":0,"value":3}]};